### ISSUE TITLE
Will this work for WM8650 ?

### ISSUE THREAD

**Issue by zhblue** [lrussell887/Debian-for-WM8505-Netbooks#3]
I have a similar notebook with WM8650  DDR 256M

**Comment by lrussell887** [comment]
I can't say for sure whether or not it will work since I do not have a WM8650 device, though given the few differences I would think that it would at least boot. You may run into some issues like screen brightness since the WM8505 uses different contrast values, and Wi-Fi since it uses GPIO to enable the card. You're of course welcome to fork this repo and make any modifications needed, and I can try to help out with any questions.
